<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MagazinesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('magazines')->delete();
        
        \DB::table('magazines')->insert(array (
            0 => 
            array (
                'id' => 3,
                'name' => 'Ceo Life',
                'slug' => 'ceo-life',
                'description' => '<p>Ceo Life</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752644899.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => 'https://past-service.s3.eu-north-1.amazonaws.com/car_photos/17/20241013152303-670be5d79387d.jpg',
                'robots' => 'index, follow',
                'order' => 4,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-07-16 05:48:20',
            ),
            1 => 
            array (
                'id' => 8,
                'name' => 'Formsante',
                'slug' => 'formsante',
                'description' => '<p>Formsante</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315692.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-07-08 07:20:32',
                'updated_at' => '2025-07-12 10:21:33',
            ),
            2 => 
            array (
                'id' => 9,
                'name' => 'Elleman',
                'slug' => 'elleman',
                'description' => '<p>Elle dergisi</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1751965352.svg',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-07-08 09:02:32',
                'updated_at' => '2025-07-08 09:02:33',
            ),
            3 => 
            array (
                'id' => 10,
                'name' => 'Maison Française',
                'slug' => 'maison-francaise',
                'description' => '<p>Maison Française</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1751965540.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-07-08 09:05:40',
                'updated_at' => '2025-07-08 09:05:40',
            ),
            4 => 
            array (
                'id' => 11,
                'name' => 'All About History',
                'slug' => 'all-about-history',
                'description' => '<p>All About History</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315467.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 21,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:17:47',
                'updated_at' => '2025-07-12 10:17:48',
            ),
            5 => 
            array (
                'id' => 12,
                'name' => 'Atlas',
                'slug' => 'atlas',
                'description' => '<p>Atlas</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315486.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 9,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:18:06',
                'updated_at' => '2025-07-12 10:18:07',
            ),
            6 => 
            array (
                'id' => 13,
                'name' => 'Atlas Tarih',
                'slug' => 'atlas-tarih',
                'description' => '<p>Atlas Tarih</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315517.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 17,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:18:37',
                'updated_at' => '2025-07-12 10:18:38',
            ),
            7 => 
            array (
                'id' => 14,
                'name' => 'Auto Show',
                'slug' => 'auto-show',
                'description' => '<p>Auto Show</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315543.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:18:54',
                'updated_at' => '2025-07-12 10:19:04',
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'B-Mag',
                'slug' => 'b-mag',
                'description' => '<p>B-Mag</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315589.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:19:49',
                'updated_at' => '2025-07-12 10:19:51',
            ),
            9 => 
            array (
                'id' => 16,
                'name' => 'Burda',
                'slug' => 'burda',
                'description' => '<p>Burda</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315612.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 19,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:20:12',
                'updated_at' => '2025-07-12 10:20:13',
            ),
            10 => 
            array (
                'id' => 17,
                'name' => 'Ev Bahçe',
                'slug' => 'ev-bahce',
                'description' => '<p>Ev Bahçe</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315656.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 18,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:20:56',
                'updated_at' => '2025-07-12 10:20:56',
            ),
            11 => 
            array (
                'id' => 18,
                'name' => 'Evim',
                'slug' => 'evim',
                'description' => '<p>Evim</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315667.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 13,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:21:07',
                'updated_at' => '2025-07-12 10:21:08',
            ),
            12 => 
            array (
                'id' => 19,
                'name' => 'Hello',
                'slug' => 'hello',
                'description' => '<p>Hello</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315719.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:21:59',
                'updated_at' => '2025-07-12 10:22:00',
            ),
            13 => 
            array (
                'id' => 20,
                'name' => 'Hey Girl',
                'slug' => 'hey-girl',
                'description' => '<p>Hey Girl</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315737.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 20,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:22:17',
                'updated_at' => '2025-07-12 10:22:18',
            ),
            14 => 
            array (
                'id' => 21,
                'name' => 'History Of War',
                'slug' => 'history-of-war',
                'description' => '<p>History Of War</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315761.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 23,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:22:41',
                'updated_at' => '2025-07-12 10:22:43',
            ),
            15 => 
            array (
                'id' => 22,
                'name' => 'How It Works',
                'slug' => 'how-it-works',
                'description' => '<p>How It Works</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315778.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 25,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:22:58',
                'updated_at' => '2025-07-12 10:22:59',
            ),
            16 => 
            array (
                'id' => 23,
                'name' => 'İstanbul Life',
                'slug' => 'istanbul-life',
                'description' => '<p>İstanbul Life</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315798.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 10,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:23:18',
                'updated_at' => '2025-07-12 10:23:18',
            ),
            17 => 
            array (
                'id' => 24,
                'name' => 'Kore Pop',
                'slug' => 'k-pop',
                'description' => '<p>Kore Pop</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315810.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 22,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:23:30',
                'updated_at' => '2025-07-12 11:31:48',
            ),
            18 => 
            array (
                'id' => 25,
                'name' => 'Popular Science',
                'slug' => 'popular-science',
                'description' => '<p>Popular Science</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315846.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 14,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:24:06',
                'updated_at' => '2025-07-12 10:24:08',
            ),
            19 => 
            array (
                'id' => 26,
                'name' => 'Pozitif',
                'slug' => 'pozitif',
                'description' => '<p>Pozitif</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315862.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:24:22',
                'updated_at' => '2025-07-12 10:24:23',
            ),
            20 => 
            array (
                'id' => 27,
                'name' => 'Start Up',
                'slug' => 'start-up',
                'description' => '<p>Start Up</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315876.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 12,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:24:36',
                'updated_at' => '2025-07-12 10:24:36',
            ),
            21 => 
            array (
                'id' => 28,
                'name' => 'Yacht',
                'slug' => 'yacht',
                'description' => '<p>Yacht</p>',
                'image' => 'https://past-service.s3.eu-north-1.amazonaws.com/bmag/1752315901.png',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'canonical_url' => NULL,
                'seo_image' => NULL,
                'robots' => 'index, follow',
                'order' => 11,
                'is_active' => 1,
                'created_at' => '2025-07-12 10:25:01',
                'updated_at' => '2025-07-12 10:25:02',
            ),
        ));
        
        
    }
}